import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import bodyParser from 'body-parser';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import config from './config/config.js';
import { syncDatabase } from './database/models/index.js';
import catalogRoutes from './routes/catalogRoutes.js';
import authRoutes from './routes/authRoutes.js';
import orderRoutes from './routes/orderRoutes.js';
import referenceDataRoutes from './routes/referenceDataRoutes.js';
import uiRoutes from './routes/uiRoutes.js';
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const app = express();
app.use(helmet());
app.use(cors());
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));
app.use('/uploads', express.static(join(__dirname, 'uploads')));
app.use('/auth', authRoutes);
app.use('/catalog', catalogRoutes);
app.use('/orders', orderRoutes);
app.use('/referenceData', referenceDataRoutes);
app.use('/ui', uiRoutes);
syncDatabase();
app.listen(config.server.port, () => {
    console.log(`Server Started On Port ${config.server.port}`);
});
export default app;